services:

  mysql:
    image: mysql:8.0

    container_name: lifesync-mysql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lifesync_ai
      MYSQL_USER: lifesync
      MYSQL_PASSWORD: lifesync_password

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
