-- =========================================================================
-- DATABASE DDL SCHEMA - AI DESTINY CALENDAR
-- =========================================================================

-- 1. USER TABLE
CREATE TABLE IF NOT EXISTS `USER` (
    User_ID VARCHAR(255) PRIMARY KEY,
    Phone_Number VARCHAR(20),
    FName VARCHAR(50),
    LName VARCHAR(50),
    Date_of_birth DATE,
    Birth_Time TIME NULL,
    Avatar_Url VARCHAR(500) NULL,
    Subscription_Status VARCHAR(20) DEFAULT 'free',
    Email VARCHAR(100) UNIQUE NOT NULL,
    Password VARCHAR(255),
    Email_Verified TINYINT(1) DEFAULT 0,
    IsSeller BOOLEAN DEFAULT FALSE,
    Shop_name VARCHAR(255),
    Shop_image VARCHAR(500),
    Shop_address VARCHAR(255),
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 2. VERIFICATION CODES TABLE
CREATE TABLE IF NOT EXISTS `VERIFICATION_CODES` (
    email VARCHAR(100) PRIMARY KEY,
    code VARCHAR(10),
    expires_at DATETIME
);

-- 3. CALENDAR EVENTS TABLE
CREATE TABLE IF NOT EXISTS `EVENT` (
    Event_ID VARCHAR(255) PRIMARY KEY,
    User_ID VARCHAR(255) NOT NULL,
    Title VARCHAR(255) NOT NULL,
    Description TEXT NULL,
    Location VARCHAR(255) NULL,
    Start_Time DATETIME NOT NULL,
    End_Time DATETIME NOT NULL,
    Category VARCHAR(50) DEFAULT 'general',
    Priority VARCHAR(10) DEFAULT 'medium',
    Color VARCHAR(7) DEFAULT '#6366f1',
    Reminder_Minutes INT DEFAULT 30,
    Is_Private TINYINT DEFAULT 0,
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (User_ID) REFERENCES `USER`(User_ID) ON DELETE CASCADE
);

-- 4. AI CHAT MESSAGES TABLE
CREATE TABLE IF NOT EXISTS `CHAT_MESSAGE` (
    Message_ID VARCHAR(255) PRIMARY KEY,
    User_ID VARCHAR(255) NOT NULL,
    Sender VARCHAR(10) NOT NULL, -- 'user' or 'ai'
    Content TEXT NOT NULL,
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (User_ID) REFERENCES `USER`(User_ID) ON DELETE CASCADE
);

-- 5. FRIENDSHIP TABLE
CREATE TABLE IF NOT EXISTS `FRIENDSHIP` (
    User_ID_1 VARCHAR(255) NOT NULL,
    User_ID_2 VARCHAR(255) NOT NULL,
    Status VARCHAR(20) DEFAULT 'pending', -- 'pending', 'accepted', 'blocked'
    Share_Level VARCHAR(20) DEFAULT 'none', -- 'none', 'free_busy', 'full'
    Requester_ID VARCHAR(255) NULL,
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (User_ID_1, User_ID_2),
    FOREIGN KEY (User_ID_1) REFERENCES `USER`(User_ID) ON DELETE CASCADE,
    FOREIGN KEY (User_ID_2) REFERENCES `USER`(User_ID) ON DELETE CASCADE,
    FOREIGN KEY (Requester_ID) REFERENCES `USER`(User_ID) ON DELETE CASCADE
);

-- 6. PREMIUM SUBSCRIPTIONS TABLE
CREATE TABLE IF NOT EXISTS `SUBSCRIPTION` (
    Subscription_ID VARCHAR(255) PRIMARY KEY,
    User_ID VARCHAR(255) NOT NULL,
    Stripe_Session_ID VARCHAR(255) NULL,
    Plan_Name VARCHAR(50) DEFAULT 'premium',
    Status VARCHAR(20) DEFAULT 'active', -- 'active', 'cancelled', 'expired'
    Start_Date DATETIME DEFAULT CURRENT_TIMESTAMP,
    End_Date DATETIME NULL,
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (User_ID) REFERENCES `USER`(User_ID) ON DELETE CASCADE
);

-- 7. INDEXES FOR PERFORMANCE OPTIMIZATION
CREATE INDEX idx_user_start ON `EVENT` (User_ID, Start_Time);
CREATE INDEX idx_user_created ON `CHAT_MESSAGE` (User_ID, Created_at);

-- 8. USER DAILY SCHEDULE BITMASK TABLE
CREATE TABLE IF NOT EXISTS `USER_DAILY_SCHEDULE` (
    User_ID VARCHAR(255) NOT NULL,
    Date DATE NOT NULL,
    Busy_Slots BIGINT UNSIGNED DEFAULT 0,
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (User_ID, Date),
    FOREIGN KEY (User_ID) REFERENCES `USER`(User_ID) ON DELETE CASCADE
);
CREATE INDEX idx_user_date ON `USER_DAILY_SCHEDULE` (User_ID, Date);

-- 9. MEETING REQUEST TABLE
CREATE TABLE IF NOT EXISTS `MEETING_REQUEST` (
    Meeting_Request_ID VARCHAR(255) PRIMARY KEY,
    Host_ID VARCHAR(255) NOT NULL,
    Title VARCHAR(255) NOT NULL,
    Duration_Minutes INT NOT NULL,
    Status VARCHAR(20) DEFAULT 'PENDING', -- 'PENDING', 'CONFIRMED', 'CANCELLED'
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Host_ID) REFERENCES `USER`(User_ID) ON DELETE CASCADE
);

-- 10. MEETING OPTIONS TABLE
CREATE TABLE IF NOT EXISTS `MEETING_OPTION` (
    Meeting_Option_ID VARCHAR(255) PRIMARY KEY,
    Meeting_Request_ID VARCHAR(255) NOT NULL,
    Start_Time DATETIME NOT NULL,
    End_Time DATETIME NOT NULL,
    Score INT DEFAULT 0,
    FOREIGN KEY (Meeting_Request_ID) REFERENCES `MEETING_REQUEST`(Meeting_Request_ID) ON DELETE CASCADE
);

-- 11. MEETING PARTICIPANTS TABLE
CREATE TABLE IF NOT EXISTS `MEETING_PARTICIPANT` (
    Meeting_Request_ID VARCHAR(255) NOT NULL,
    User_ID VARCHAR(255) NOT NULL,
    Status VARCHAR(20) DEFAULT 'INVITED', -- 'INVITED', 'ACCEPTED', 'DECLINED'
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (Meeting_Request_ID, User_ID),
    FOREIGN KEY (Meeting_Request_ID) REFERENCES `MEETING_REQUEST`(Meeting_Request_ID) ON DELETE CASCADE,
    FOREIGN KEY (User_ID) REFERENCES `USER`(User_ID) ON DELETE CASCADE
);

-- 12. MEETING VOTES TABLE (Supports multiple votes per participant)
CREATE TABLE IF NOT EXISTS `MEETING_VOTE` (
    Meeting_Request_ID VARCHAR(255) NOT NULL,
    User_ID VARCHAR(255) NOT NULL,
    Meeting_Option_ID VARCHAR(255) NOT NULL,
    PRIMARY KEY (Meeting_Request_ID, User_ID, Meeting_Option_ID),
    FOREIGN KEY (Meeting_Request_ID) REFERENCES `MEETING_REQUEST`(Meeting_Request_ID) ON DELETE CASCADE,
    FOREIGN KEY (User_ID) REFERENCES `USER`(User_ID) ON DELETE CASCADE,
    FOREIGN KEY (Meeting_Option_ID) REFERENCES `MEETING_OPTION`(Meeting_Option_ID) ON DELETE CASCADE
);

-- 13. NOTIFICATION TABLE
CREATE TABLE IF NOT EXISTS `NOTIFICATION` (
    Notification_ID VARCHAR(255) PRIMARY KEY,
    User_ID VARCHAR(255) NOT NULL,
    Type VARCHAR(50) NOT NULL,
    Title VARCHAR(255) NOT NULL,
    Content TEXT NOT NULL,
    Link VARCHAR(255) NULL,
    Is_Read TINYINT DEFAULT 0,
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (User_ID) REFERENCES `USER`(User_ID) ON DELETE CASCADE
);
